services:
  postgres:
    container_name: postgres-sql-falai
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: falai

    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - falai
    restart: unless-stopped
  keycloak:
    container_name: keycloak-falai
    image: quay.io/keycloak/keycloak:26.0.0
    ports:
      - 9090:8080
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    networks:
      - falai
    command:
      - "start-dev"

volumes:
  postgres:
    driver: local

networks:
  falai:
    driver: bridge
    